# Generated by Django 6.0 on 2025-12-29 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('calorias', models.IntegerField()),
                ('proteinas', models.FloatField()),
                ('carboidratos', models.FloatField()),
                ('colesterol', models.FloatField(blank=True, null=True)),
                ('fibra', models.FloatField(blank=True, null=True)),
                ('sodio', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('calorias', models.IntegerField()),
                ('proteinas', models.FloatField()),
                ('carboidratos', models.FloatField()),
                ('sodio', models.FloatField(blank=True, null=True)),
                ('gordura', models.FloatField(blank=True, null=True)),
                ('gordurasaturada', models.FloatField(blank=True, null=True)),
                ('fibra', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
