# Generated by Django 6.0 on 2026-01-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentobase',
            name='carboidratos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alimentobase',
            name='proteinas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alimentocustomizado',
            name='carboidratos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alimentocustomizado',
            name='proteinas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
