# Generated by Django 6.0 on 2025-12-29 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('aluno', 'Aluno'), ('profissional', 'Profissional')], max_length=20)),
                ('sexo', models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=10)),
                ('altura', models.IntegerField()),
                ('cintura', models.IntegerField()),
                ('pescoco', models.IntegerField()),
                ('objetivo', models.CharField(choices=[('cutting', 'Cutting'), ('bulking', 'Bulking'), ('manutenção', 'Manutenção')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfissinalAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('profissional', 'aluno')},
            },
        ),
    ]
