# Generated by Django 6.0 on 2026-01-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profissionalaluno_delete_profissinalaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idade',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cintura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('cutting', 'Cutting'), ('bulking', 'Bulking'), ('manutenção', 'Manutenção')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pescoco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=10, null=True),
        ),
    ]
