# Generated by Django 6.0 on 2026-02-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_idade_alter_perfil_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='atividade',
            field=models.CharField(blank=True, choices=[('cutting', 'Cutting'), ('bulking', 'Bulking'), ('manutenção', 'Manutenção')], max_length=20, null=True),
        ),
    ]
