# Generated by Django 6.0 on 2026-02-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='atividade',
            field=models.CharField(blank=True, choices=[('sedentario', 'Sedentário'), ('moderado', 'Moderado'), ('intenso', 'Intenso'), ('leve', 'Leve')], max_length=20, null=True),
        ),
    ]
