# Generated by Django 6.0 on 2026-02-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfil_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
