# Generated by Django 6.0 on 2026-03-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_perfil_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('profissional', 'Profissional'), ('usuario_comum', 'Usuário Comum')], max_length=20),
        ),
    ]
