# Generated by Django 6.0 on 2025-12-29 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias', models.IntegerField()),
                ('proteinas', models.FloatField()),
                ('carboidratos', models.FloatField()),
                ('gordura', models.FloatField()),
                ('datacriacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('alimentobase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alimentos.alimentobase')),
                ('alimentocustomizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alimentos.alimentocustomizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to=settings.AUTH_USER_MODEL)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='dieta.dieta')),
            ],
        ),
    ]
