# Generated by Django 6.0 on 2026-03-25 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dieta',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('usuario',), name='uma_dieta_ativa_por_usuario'),
        ),
    ]
