# Generated by Django 6.0 on 2026-04-08 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0002_dieta_uma_dieta_ativa_por_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='calorias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='carboidratos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='gordura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='proteinas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieta.dieta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consumoalimento',
            name='refeicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='dieta.refeicao'),
        ),
    ]
