# Generated by Django 6.0 on 2026-07-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0003_alter_dieta_calorias_alter_dieta_carboidratos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='dieta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='dieta.dieta'),
        ),
    ]
