# Generated by Django 6.0 on 2026-07-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0004_alter_refeicao_dieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='nome',
            field=models.CharField(default='Minha dieta', max_length=50),
        ),
    ]
